#!/usr/bin/env python3
"""
bridge.py — discover / validate / summarize a companion bridge.

A bridge is a folder with a bridge.md manifest (containing a fenced ```json block)
that declares which engine hooks the companion overrides and where its files are.
The engine reads the manifest at load and uses an override where present, else the
Mythic/AC default.

Commands:
  summary  <bridge_dir>            Print overrides-vs-defaults for the 9 hooks (NAMES only)
  brief    <bridge_dir> [--into F] Print each override's OPERATIVE digest (CONTENTS) so boot loads
                                   the imperative, not just the name. --into rewrites the marked
                                   block in orchestration doc F (generated, never hand-synced).
  validate <bridge_dir> [--doc F]  Check the manifest + declared files + roll-test tables, AND that
                                   each imperative hook carries an <!-- OPERATIVE:<hook> --> block;
                                   --doc F also checks F embeds the generated digest.
  manifest <bridge_dir>            Print the parsed JSON manifest
"""
import json, os, re, sys, glob

HOOKS = ["resolve","generate:character","generate:element","meaning","chaos",
         "themes","world-tick","seeds","adventure-ingest"]

# Which manifest file-key carries each hook's prose (so brief/validate can find the imperative).
HOOK_FILE_KEY = {
    "resolve": "system_profile", "meaning": "interpretation", "chaos": "chaos",
    "themes": "themes", "world-tick": "subsystems", "seeds": "seeds",
    "generate:character": "generators", "generate:element": "generators",
}
# Hooks whose imperative MUST be surfaced at the moment of action (validate enforces a digest).
IMPERATIVE_HOOKS = {"resolve", "world-tick", "meaning"}
DIGEST_BEGIN = "<!-- BEGIN OPERATIVE DIGEST (generated by `bridge.py brief`; do not hand-edit) -->"
DIGEST_END   = "<!-- END OPERATIVE DIGEST -->"

def extract_operative(path, hook):
    """Pull the text of a hook file's <!-- OPERATIVE:<hook> --> ... <!-- /OPERATIVE --> block."""
    try: txt = open(path, encoding="utf-8").read()
    except OSError: return None
    m = re.search(r"<!--\s*OPERATIVE:" + re.escape(hook) + r"\s*-->(.*?)<!--\s*/OPERATIVE\s*-->",
                  txt, re.DOTALL)
    return m.group(1).strip() if m else None

def read_manifest(bdir):
    p = os.path.join(bdir, "bridge.md")
    if not os.path.exists(p): sys.exit(f"No bridge.md in {bdir}")
    txt = open(p, encoding="utf-8").read()
    m = re.search(r"```json\s*(\{.*?\})\s*```", txt, re.DOTALL)
    if not m: sys.exit("bridge.md has no ```json manifest block")
    try: return json.loads(m.group(1))
    except Exception as e: sys.exit(f"manifest JSON error: {e}")

def _manifest_safe(bdir):
    """read_manifest without exiting — returns {} when there's no usable bridge."""
    try: return read_manifest(bdir)
    except SystemExit: return {}

def char_gen(bdir):
    """Resolve the companion's NEW-character generation override, or None for the engine
    default (AC Character Crafter). Reads manifest.generators_map.character:
      {"mode": "replace"|"conjunction"|"default", "table": "generators/x.json", "note": "<lore>"}
    'replace' uses the companion generator INSTEAD of the AC Crafter; 'conjunction' uses BOTH;
    a bare note (no table) = lore-based generation the GM performs from setting-canon. Table
    paths are returned absolute. Only honored when 'generate:character' is in overrides."""
    if not bdir: return None
    man = _manifest_safe(bdir)
    if not man: return None
    gm = (man.get("generators_map") or {}).get("character")
    if not gm or "generate:character" not in man.get("overrides", []): return None
    out = dict(gm); out.setdefault("mode", "conjunction")
    if out.get("table"): out["table"] = os.path.join(bdir, out["table"])
    return out

def cmd_summary(bdir):
    man = read_manifest(bdir); ov = set(man.get("overrides", []))
    print(f"Companion: {man.get('companion','?')}   engine: {man.get('engine','?')}")
    for h in HOOKS:
        hit = h in ov or any(o.startswith("generate:") for o in ov) if h.startswith("generate:") else h in ov
        print(f"  {'OVERRIDE' if h in ov else 'default ':8}  {h}")

def build_brief(bdir):
    """Assemble the operative digest: per overridden hook, its OPERATIVE block (CONTENTS),
    or a one-line pointer. Returns Markdown text suitable for boot stdout or inlining."""
    man = read_manifest(bdir); files = man.get("files", {}); ov = man.get("overrides", [])
    out = [f"**Operative digest — {man.get('companion','?')}.** The imperatives behind the "
           "overridden hooks, loaded where they fire (generated by `bridge.py brief`; do not hand-edit)."]
    for hook in ov:
        rel = files.get(HOOK_FILE_KEY.get(hook, ""), None)
        digest = extract_operative(os.path.join(bdir, rel), hook) if rel else None
        if digest:
            out.append(f"\n#### {hook}  ·  `{rel}`\n{digest}")
        elif hook in IMPERATIVE_HOOKS:
            out.append(f"\n#### {hook}  ·  `{rel or '?'}`\n> ⚠ no `<!-- OPERATIVE:{hook} -->` block — run `bridge.py validate`.")
        else:
            out.append(f"- {hook} → `{rel or '(generator override)'}` (read the file)")
    return "\n".join(out)

def cmd_brief(bdir, into=None):
    body = build_brief(bdir)
    if not into:
        print(body); return
    if not os.path.exists(into): sys.exit(f"--into target {into} not found.")
    txt = open(into, encoding="utf-8").read()
    block = DIGEST_BEGIN + "\n" + body + "\n" + DIGEST_END
    pat = re.escape(DIGEST_BEGIN) + r".*?" + re.escape(DIGEST_END)
    if not re.search(pat, txt, re.DOTALL):
        sys.exit(f"No digest markers in {into}. Add this pair where the digest should live:\n{DIGEST_BEGIN}\n{DIGEST_END}")
    open(into, "w", encoding="utf-8").write(re.sub(pat, lambda m: block, txt, flags=re.DOTALL))
    print(f"Rendered operative digest into {into} ({len(body)} chars across {body.count('####')} hook block(s)).")

def cmd_validate(bdir, doc=None):
    man = read_manifest(bdir); problems = []
    files = man.get("files", {})
    for key, rel in files.items():
        if not os.path.exists(os.path.join(bdir, rel)):
            problems.append(f"missing file '{rel}' (declared as {key})")
    for h in man.get("overrides", []):
        if h not in HOOKS and not h.startswith("generate:"):
            problems.append(f"unknown hook '{h}'")
    # enforcement: an overridden imperative hook must carry an OPERATIVE block boot can surface
    for h in man.get("overrides", []):
        if h in IMPERATIVE_HOOKS:
            rel = files.get(HOOK_FILE_KEY.get(h, ""), None)
            if not rel or not extract_operative(os.path.join(bdir, rel), h):
                problems.append(f"hook '{h}' has no <!-- OPERATIVE:{h} --> block in "
                                f"{rel or '(no file mapped)'} — boot can't surface its imperative")
    if doc:                              # optional: the orchestration doc must embed the digest
        if not os.path.exists(doc): problems.append(f"--doc {doc} not found")
        elif DIGEST_BEGIN not in open(doc, encoding="utf-8").read():
            problems.append(f"orchestration doc {doc} has no OPERATIVE DIGEST block "
                            f"(run `bridge.py brief {bdir} --into {doc}`)")
    # roll-test any generator tables
    tested = 0
    for f in glob.glob(os.path.join(bdir, "generators", "*.json")):
        try:
            t = json.load(open(f))
            if t.get("type","").startswith("list_"):
                cov = sum(e["max"]-e["min"]+1 for e in t["entries"])
                need = 100 if t["type"]=="list_d100" else 10
                if cov != need: problems.append(f"{os.path.basename(f)}: coverage {cov}/{need}")
                tested += 1
        except Exception as e:
            problems.append(f"{os.path.basename(f)}: {e}")
    if problems:
        print("INVALID:"); [print("  X", p) for p in problems]; sys.exit(1)
    print(f"Bridge valid ✓  ({len(man.get('overrides',[]))} overrides, {tested} generator tables roll-tested)")

def cmd_manifest(bdir):
    print(json.dumps(read_manifest(bdir), indent=2))

def main():
    a = sys.argv[1:]
    if not a or a[0] in ("-h","--help"): print(__doc__); return
    if len(a) < 2: sys.exit("Need a bridge directory.")
    cmd, bdir = a[0], a[1]
    def opt(flag): return a[a.index(flag)+1] if flag in a else None
    if cmd == "summary": cmd_summary(bdir)
    elif cmd == "manifest": cmd_manifest(bdir)
    elif cmd == "brief": cmd_brief(bdir, into=opt("--into"))
    elif cmd == "validate": cmd_validate(bdir, doc=opt("--doc"))
    else: sys.exit(f"Unknown command '{cmd}'")

if __name__ == "__main__":
    main()
